title: "emopedia's plugins"
description: "View documentation for emopedia's plugins."

remote_theme: just-the-docs/just-the-docs@v0.12.0

search_enabled: true
heading_anchors: true

aux_links:
  "emopedia on GitHub":
    - "https://github.com/emopedia"

aux_links_new_tab: true

color_scheme: light

nav_sort: case_insensitive

back_to_top: true
back_to_top_text: "Back to top"
